services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=test'
      - 'POSTGRES_PASSWORD=test'
      - 'POSTGRES_USER=test'
    ports:
      - '5432:5432'
  kafka:
    image: 'apache/kafka:latest'
    ports:
      - '9092:9092'